export const constantLinks = [
  {
    title: "plc.ua",
    shortTitle: "plc",
    href: "https://plc.ua/auctions/",
    price: 100,
  },
  {
    title: "en.bidfax.info",
    shortTitle: "bidfaxEn",
    href: "https://en.bidfax.info/",
    price: 100,
  },
  {
    title: "ucars.pro",
    shortTitle: "ucars",
    href: "https://ucars.pro/",
    price: 100,
  },
  {
    title: "carfast.express",
    shortTitle: "carfast",
    href: "https://carfast.express/",
    price: 100,
  },
  {
    title: "bidfax.info",
    shortTitle: "bidfax",
    href: "https://bidfax.info/",
    price: 100,
  },
  {
    title: "auto.ria.com",
    shortTitle: "autoRia",
    href: "https://auto.ria.com/",
    price: 100,
  },
  {
    title: "autobidmaster.com",
    shortTitle: "autobidmaster",
    href: "https://www.autobidmaster.com",
    price: 100,
  },
  {
    title: "vincleaner.com",
    shortTitle: "vincleaner",
    href: "https://vincleaner.com/",
    price: 100,
  },
  {
    title: "autohistory.online",
    shortTitle: "autohistory",
    href: "https://autohistory.online/",
    price: 100,
  },
  {
    title: "americamotors.com",
    shortTitle: "americamotors",
    href: "https://americamotors.com/",
    price: 100,
  },
  {
    title: "auctions.carsimulcast.com",
    shortTitle: "carsimulcast",
    href: "https://auctions.carsimulcast.com/",
    price: 100,
  },
  {
    title: "bid.cars",
    shortTitle: "bidCars",
    href: "https://bid.cars/",
    price: 100,
  },
  {
    title: "auctionauto.fr",
    shortTitle: "auctionauto",
    href: "https://auctionauto.fr/",
    price: 100,
  },
  {
    title: "vinspy.eu",
    shortTitle: "vinspy",
    href: "https://vinspy.eu/",
    price: 100,
  },
  {
    title: "autoastat.com",
    shortTitle: "autoastat",
    href: "https://autoastat.com",
    price: 100,
  },
  {
    title: "carcheck.by",
    shortTitle: "carcheck",
    href: "https://carcheck.by",
    price: 100,
  },
  {
    title: "autozona.com.ua",
    shortTitle: "autozona",
    href: "https://autozona.com.ua",
    price: 100,
  },
];
