import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import { Header, Footer } from "components/Layout";
import "app/globals.scss";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--inter",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale}>
      <body className={`${inter.variable} ${montserrat.variable} font-primary font-normal`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
